# Generated by Django 3.1.2 on 2020-11-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='position_id',
            field=models.JSONField(default=list),
        ),
    ]
